//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flux.ConsoleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrimitivesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrimitivesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FluxSDK.ConsoleApp.Properties.PrimitivesResource", typeof(PrimitivesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;start&quot;: [
        ///                            0.05,
        ///                            -0.183,
        ///                            -0.091
        ///                        ],
        ///                        &quot;middle&quot;: [
        ///                            -0.0558,
        ///                            -0.23,
        ///                            -0.345
        ///                        ],
        ///                        &quot;end&quot;: [
        ///                            -0.0288,
        ///                            -0.017,
        ///                            0.12
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string arc {
            get {
                return ResourceManager.GetString("arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;origin&quot;: [
        ///                            0,
        ///                            0,
        ///                            0
        ///                        ],
        ///                        &quot;dimensions&quot;: [
        ///                            10,
        ///                            10,
        ///                            10
        ///                        ],
        ///                        &quot;primitive&quot;: &quot;block&quot;
        ///                    }
        ///                }.
        /// </summary>
        internal static string block {
            get {
                return ResourceManager.GetString("block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;origin&quot;: [
        ///                            0.5,
        ///                            1.2,
        ///                            -8.2
        ///                        ],
        ///                        &quot;radius&quot;: 12.1,
        ///                        &quot;primitive&quot;: &quot;circle&quot;
        ///                    }.
        /// </summary>
        internal static string circle {
            get {
                return ResourceManager.GetString("circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;degree&quot;: 3,
        ///                        &quot;knots&quot;: [
        ///                            0,
        ///                            0,
        ///                            0,
        ///                            0,
        ///                            1,
        ///                            1,
        ///                            1,
        ///                            1
        ///                        ],
        ///                        &quot;controlPoints&quot;: [
        ///                            [
        ///                                1,
        ///                                30,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string curve {
            get {
                return ResourceManager.GetString("curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;origin&quot;: [
        ///                            0.5,
        ///                            1.2,
        ///                            -8.2
        ///                        ],
        ///                        &quot;majorRadius&quot;: 15.8,
        ///                        &quot;minorRadius&quot;: 12.1,
        ///                        &quot;primitive&quot;: &quot;ellipse&quot;
        ///                    }.
        /// </summary>
        internal static string ellipse {
            get {
                return ResourceManager.GetString("ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;start&quot;: [
        ///                            -10,
        ///                            0,
        ///                            25
        ///                        ],
        ///                        &quot;end&quot;: [
        ///                            10.5,
        ///                            -15,
        ///                            -15.25
        ///                        ],
        ///                        &quot;primitive&quot;: &quot;line&quot;
        ///                    }.
        /// </summary>
        internal static string line {
            get {
                return ResourceManager.GetString("line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;vertices&quot;: [
        ///                            [
        ///                                0,
        ///                                0,
        ///                                0
        ///                            ],
        ///                            [
        ///                                0,
        ///                                6,
        ///                                0
        ///                            ],
        ///                            [
        ///                                6,
        ///                                0,
        ///                            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mesh {
            get {
                return ResourceManager.GetString("mesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;point&quot;: [
        ///                            10,
        ///                            10,
        ///                            10
        ///                        ],
        ///                        &quot;primitive&quot;: &quot;point&quot;
        ///                    }
        ///                }.
        /// </summary>
        internal static string point {
            get {
                return ResourceManager.GetString("point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;curves&quot;: [
        ///                            {
        ///                                &quot;start&quot;: [
        ///                                    1,
        ///                                    1,
        ///                                    1
        ///                                ],
        ///                                &quot;end&quot;: [
        ///                                    0,
        ///                                    0,
        ///                                    0
        ///                                ],
        ///                                &quot;primitive&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string polycurve {
            get {
                return ResourceManager.GetString("polycurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;points&quot;: [
        ///                            [
        ///                                0,
        ///                                0,
        ///                                0
        ///                            ],
        ///                            [
        ///                                12,
        ///                                15,
        ///                                26
        ///                            ],
        ///                            [
        ///                                6,
        ///                                25,
        ///                          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string polyline {
            get {
                return ResourceManager.GetString("polyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;origin&quot;: [
        ///                            -2.5,
        ///                            0.5,
        ///                            -1.3
        ///                        ],
        ///                        &quot;dimensions&quot;: [
        ///                            12.1,
        ///                            16.8
        ///                        ],
        ///                        &quot;primitive&quot;: &quot;rectangle&quot;
        ///                    }.
        /// </summary>
        internal static string rectangle {
            get {
                return ResourceManager.GetString("rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                        &quot;origin&quot;: [
        ///                            0,
        ///                            0,
        ///                            0
        ///                        ],
        ///                        &quot;radius&quot;: 10,
        ///                        &quot;primitive&quot;: &quot;sphere&quot;
        ///                    }.
        /// </summary>
        internal static string sphere {
            get {
                return ResourceManager.GetString("sphere", resourceCulture);
            }
        }
    }
}
