//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flux.SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FluxApiData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FluxApiData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flux.SDK.Properties.FluxApiData", typeof(FluxApiData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /capability.
        /// </summary>
        internal static string CapabilityUrl {
            get {
                return ResourceManager.GetString("CapabilityUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cells.
        /// </summary>
        internal static string CellBaseUrl {
            get {
                return ResourceManager.GetString("CellBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cells/{0}.
        /// </summary>
        internal static string CellIdUrl {
            get {
                return ResourceManager.GetString("CellIdUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /p/{0}/api/datatable/v1/cells/{1}.
        /// </summary>
        internal static string CellUrl {
            get {
                return ResourceManager.GetString("CellUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /cells/{0}/ref.
        /// </summary>
        internal static string CellValueRef {
            get {
                return ResourceManager.GetString("CellValueRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p/{0}/api/blockexec?block=flux-internal/parasolid/Parasolid.
        /// </summary>
        internal static string ConvertUrl {
            get {
                return ResourceManager.GetString("ConvertUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auth.
        /// </summary>
        internal static string CookiesAuthName {
            get {
                return ResourceManager.GetString("CookiesAuthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flux_token.
        /// </summary>
        internal static string CookiesTokenName {
            get {
                return ResourceManager.GetString("CookiesTokenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /p/{0}/api/datatable/v1.
        /// </summary>
        internal static string DataTableAPIUrl {
            get {
                return ResourceManager.GetString("DataTableAPIUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flux.io.
        /// </summary>
        internal static string DefaultServer {
            get {
                return ResourceManager.GetString("DefaultServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://flux.io.
        /// </summary>
        internal static string DefaultServerUrl {
            get {
                return ResourceManager.GetString("DefaultServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads/.
        /// </summary>
        internal static string DownloadUrl {
            get {
                return ResourceManager.GetString("DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/env.
        /// </summary>
        internal static string EnvUrl {
            get {
                return ResourceManager.GetString("EnvUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux\fluxData.bin.
        /// </summary>
        internal static string FluxCookiesData {
            get {
                return ResourceManager.GetString("FluxCookiesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forgotpw.
        /// </summary>
        internal static string ForgetUrl {
            get {
                return ResourceManager.GetString("ForgetUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept-Encoding.
        /// </summary>
        internal static string HeaderAcceptEncoding {
            get {
                return ResourceManager.GetString("HeaderAcceptEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-encoding.
        /// </summary>
        internal static string HeaderContentEncoding {
            get {
                return ResourceManager.GetString("HeaderContentEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Auxiliary-Return.
        /// </summary>
        internal static string HeadersAux {
            get {
                return ResourceManager.GetString("HeadersAux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Plugin-Host-File.
        /// </summary>
        internal static string HeadersHostFile {
            get {
                return ResourceManager.GetString("HeadersHostFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Plugin-Host.
        /// </summary>
        internal static string HeadersHostName {
            get {
                return ResourceManager.GetString("HeadersHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Plugin-Host-Version.
        /// </summary>
        internal static string HeadersHostVersion {
            get {
                return ResourceManager.GetString("HeadersHostVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Options.
        /// </summary>
        internal static string HeadersOpt {
            get {
                return ResourceManager.GetString("HeadersOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Plugin-Platform.
        /// </summary>
        internal static string HeadersPluginPlatform {
            get {
                return ResourceManager.GetString("HeadersPluginPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Plugin-Version.
        /// </summary>
        internal static string HeadersPluginVersion {
            get {
                return ResourceManager.GetString("HeadersPluginVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Request-Marker.
        /// </summary>
        internal static string HeadersRequestMarker {
            get {
                return ResourceManager.GetString("HeadersRequestMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux-Request-Token.
        /// </summary>
        internal static string HeadersRequestToken {
            get {
                return ResourceManager.GetString("HeadersRequestToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://community.flux.io/.
        /// </summary>
        internal static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostProgramMainFile.
        /// </summary>
        internal static string HostProgramMainFile {
            get {
                return ResourceManager.GetString("HostProgramMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HostProgramVersion.
        /// </summary>
        internal static string HostProgramVersion {
            get {
                return ResourceManager.GetString("HostProgramVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/login.
        /// </summary>
        internal static string LoginUrl {
            get {
                return ResourceManager.GetString("LoginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home/#!/me.
        /// </summary>
        internal static string MyProfileUrl {
            get {
                return ResourceManager.GetString("MyProfileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /p/{0}.
        /// </summary>
        internal static string ProjectDeleteUrl {
            get {
                return ResourceManager.GetString("ProjectDeleteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /p/{0}/api/meta.
        /// </summary>
        internal static string ProjectMetaUrl {
            get {
                return ResourceManager.GetString("ProjectMetaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/projects.
        /// </summary>
        internal static string ProjectsUrl {
            get {
                return ResourceManager.GetString("ProjectsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ref.
        /// </summary>
        internal static string RefUrl {
            get {
                return ResourceManager.GetString("RefUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signup/.
        /// </summary>
        internal static string RegisterUrl {
            get {
                return ResourceManager.GetString("RegisterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r/#!/release-notes.
        /// </summary>
        internal static string ReleaseNotesUrl {
            get {
                return ResourceManager.GetString("ReleaseNotesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux.Serialization.dll.
        /// </summary>
        internal static string SerializationDll {
            get {
                return ResourceManager.GetString("SerializationDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/token.
        /// </summary>
        internal static string TokenUrl {
            get {
                return ResourceManager.GetString("TokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primitive.
        /// </summary>
        internal static string TypeKeyName {
            get {
                return ResourceManager.GetString("TypeKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-key-update.
        /// </summary>
        internal static string UpdateKeyName {
            get {
                return ResourceManager.GetString("UpdateKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /value/{0}.
        /// </summary>
        internal static string ValueRefUrl {
            get {
                return ResourceManager.GetString("ValueRefUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /p/{0}/wsurl?reason={1}.
        /// </summary>
        internal static string WebSocketUrl {
            get {
                return ResourceManager.GetString("WebSocketUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/whoami.
        /// </summary>
        internal static string WhoAmIUrl {
            get {
                return ResourceManager.GetString("WhoAmIUrl", resourceCulture);
            }
        }
    }
}
