//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flux.SDK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Flux.SDK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converters.
        /// </summary>
        internal static string ConvertersPath {
            get {
                return ResourceManager.GetString("ConvertersPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux\data.bin.
        /// </summary>
        internal static string CredentialsPath {
            get {
                return ResourceManager.GetString("CredentialsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string EmailString {
            get {
                return ResourceManager.GetString("EmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address should not be empty. Please enter your email address..
        /// </summary>
        internal static string EmptyFieldsMsg {
            get {
                return ResourceManager.GetString("EmptyFieldsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to activeServerURL.
        /// </summary>
        internal static string HostsActiveServerURL {
            get {
                return ResourceManager.GetString("HostsActiveServerURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosts.xml.
        /// </summary>
        internal static string HostsFileName {
            get {
                return ResourceManager.GetString("HostsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serverURL.
        /// </summary>
        internal static string HostsServerListURL {
            get {
                return ResourceManager.GetString("HostsServerListURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux.config.
        /// </summary>
        internal static string LogCofigFileName {
            get {
                return ResourceManager.GetString("LogCofigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string PasswordString {
            get {
                return ResourceManager.GetString("PasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flux.SDK.
        /// </summary>
        internal static string SDKName {
            get {
                return ResourceManager.GetString("SDKName", resourceCulture);
            }
        }
    }
}
